name: DMCCombat
version: 2.0.0
main: com.diplomaticamc.dmccombat.DMCCombat
api-version: 1.20
authors: [ Foksha, Error110, Windows10Laptop, CorruptedGreed, StoffeH, Starwars_16 ]
description: Combat plugin for DiplomaticaMC. DMCCombat is the combination of development work by DiplomaticaMC and EarthMC's deprecated public combat plugin repository (EMCCOM).
depend:
  - Towny
commands:
  combattag:
    description: Assists admins in tagging and untagging users.
    permission: dmccombat.command.combattag
    permission-message: You do not have permission to run this command!
    usage: /combattag help
  combatpref:
  spawnprotpref:
  newbie:
    description: Newbie protection interface.
    usage: /newbie
  protectiontime:
    description: View remaining protection time!
    usage: /protectiontime