name: DMCCombat
version: 2.0.0-UNSAFE
main: com.diplomaticamc.dmccombat.DMCCombat
api-version: 1.19
authors: [ Foksha, Error110, Windows10Laptop, CorruptedGreed, StoffeH, Starwars_16 ]
description: A combat plugin!
depend:
  - Towny
commands:
  combattag:
    description: Assists admins in tagging and untagging users.
    permission: dmccombat.command.combattag
    permission-message: You do not have permission to run this command!
    usage: /combattag help
  combatpref:
  spawnprotpref:
  newbie:
  protectiontime: